nsims = 5000

fipsToState = {
    0:"0",
    2:"AK",
    1:"AL",
    5:"AR",
    60:"AS",
    4:"AZ",
    6:"CA",
    8:"CO",
    9:"CT",
    11:"DC",
    10:"DE",
    12:"FL",
    13:"GA",
    66:"GU",
    15:"HI",
    19:"IA",
    16:"ID",
    17:"IL",
    18:"IN",
    20:"KS",
    21:"KY",
    22:"LA",
    25:"MA",
    24:"MD",
    23:"ME",
    26:"MI",
    27:"MN",
    29:"MO",
    28:"MS",
    30:"MT",
    37:"NC",    
    38:"ND",
    31:"NE",
    33:"NH",
    34:"NJ",
    35:"NM",
    32:"NV",
    36:"NY",
    39:"OH",
    40:"OK",
    41:"OR",
    42:"PA",
    72:"PR",
    44:"RI",
    45:"SC",
    46:"SD",
    47:"TN",
    48:"TX",
    49:"UT",
    51:"VA",
    78:"VI",
    50:"VT",
    53:"WA",
    55:"WI",
    54:"WV",
    56:"WY"
}

col_names_outlook = [
    'otlk_timestamp','wfo_st_list',
        'toy_sin','toy_cos','maxhaz','medhaz','minhaz','popwfo','maxtor','medtor','mintor',
        'areator', 'area2tor', 'area5tor', 'area10tor', 'area15tor', 'area30tor', 'area45tor', 'area60tor',
        'areacigtor', 'areacig0tor', 'areacig1tor', 'areacig2tor',
        'poptor', 'pop2tor', 'pop5tor', 'pop10tor', 'pop15tor', 'pop30tor', 'pop45tor', 'pop60tor',
        'popcig0tor', 'popcig1tor', 'popcig2tor',
        'poptordensity',
        'maxhail','medhail','minhail',
        'areahail', 'area5hail', 'area15hail', 'area30hail', 'area45hail', 'area60hail',
        'areacighail', 'areacig0hail', 'areacig1hail', 'areacig2hail',
        'pophail', 'pop5hail', 'pop15hail', 'pop30hail', 'pop45hail', 'pop60hail',
        'popcig0hail', 'popcig1hail', 'popcig2hail',
        'pophaildensity',
        'maxwind','medwind','minwind',
        'areawind', 'area5wind', 'area15wind', 'area30wind', 'area45wind', 'area60wind',
        'areacigwind', 'areacig0wind', 'areacig1wind', 'areacig2wind',
        'popwind', 'pop5wind', 'pop15wind', 'pop30wind', 'pop45wind', 'pop60wind',
        'popcig0wind', 'popcig1wind', 'popcig2wind',
        'popwinddensity'
]

col_names_wind = ['maxwind', 'medwind', 'minwind', 'areawind', 'area5wind', 'area15wind',
       'area30wind', 'area45wind', 'area60wind', 'areacigwind', 'areacig0wind',
       'areacig1wind', 'areacig2wind', 'popwind', 'pop5wind', 'pop15wind',
       'pop30wind', 'pop45wind', 'pop60wind', 'popcig0wind', 'popcig1wind',
       'popcig2wind', 'popwinddensity', 'wfo', 'doy', 'maxct', 'medct',
       'maxhourct', 'medhourct', 'hourofmax_sin', 'hourofmax_cos', 'sumct',
       'sumhourct', 'sumpopct', 'sumhourpopct', 'maxpopct', 'medpopct',
       'maxhourpopct', 'medhourpopct']

col_names_hail = ['maxhail', 'medhail', 'minhail', 'areahail', 'area5hail', 'area15hail',
       'area30hail', 'area45hail', 'area60hail', 'areacighail', 'areacig0hail',
       'areacig1hail', 'areacig2hail', 'pophail', 'pop5hail', 'pop15hail',
       'pop30hail', 'pop45hail', 'pop60hail', 'popcig0hail', 'popcig1hail',
       'popcig2hail', 'pophaildensity', 'wfo', 'doy', 'maxct', 'medct',
       'maxhourct', 'medhourct', 'hourofmax_sin', 'hourofmax_cos', 'sumct',
       'sumhourct', 'sumpopct', 'sumhourpopct', 'maxpopct', 'medpopct',
       'maxhourpopct', 'medhourpopct']

col_names_href = [
        'otlk_timestamp','wfo_st_list',
        'maxct','medct',
        'maxhourct','medhourct',
        'hourofmax_sin','hourofmax_cos',
        'sumct','sumhourct','sumpopct','sumhourpopct',
        'maxpopct','medpopct','maxhourpopct','medhourpopct'
]

# 0 non-sig, 1 sig
mags = [0,1]
levs = [0,1,2,3]

cig_dists = {
    'wind': 
    {
        '0': [0.94,0.06],
        '1': [0.87,0.13],
        '2': [0.77,0.23],
        '3': [0.66,0.34]
    },
    'hail': 
    {
        '0': [0.92,0.08],
        '1': [0.83,0.17],
        '2': [0.75,0.25],
        # dummy
        '3': [0.65,0.35]
    }
}

#### CWA-ST size categorized

small_cwast = ['ABQAZ',
 'ABRMN',
 'ABRND',
 'AKQMD',
 'ALYCT',
 'ALYMA',
 'ALYVT',
 'AMANM',
 'ARXIL',
 'BISMT',
 'BISSD',
 'BMXMS',
 'BOINV',
 'BOXNH',
 'BOXRI',
 'BTVNH',
 'BUFPA',
 'CLEPA',
 'CTPMD',
 'CTPWV',
 'CYSCO',
 'DDCCO',
 'DDCOK',
 'DMXMO',
 'DTXOH',
 'DVNMO',
 'EAXNE',
 'EPZAZ',
 'FFCAL',
 'FGFSD',
 'FWDOK',
 'GJTAZ',
 'GJTNM',
 'GLDNE',
 'GSPTN',
 'GYXMA',
 'GYXVT',
 'HUNMS',
 'HUNTN',
 'ICTOK',
 'INDIL',
 'JANAR',
 'JKLTN',
 'JKLVA',
 'KEYFL',
 'LBFCO',
 'LMKTN',
 'LUBNM',
 'LWXDC',
 'LZKMS',
 'LZKOK',
 'MEGAL',
 'MEGMO',
 'MFRNV',
 'MKXIL',
 'MPXIA',
 'MPXSD',
 'MQTWI',
 'MRXAL',
 'MRXGA',
 'MRXKY',
 'MRXNC',
 'MSOOR',
 'OAXKS',
 'OAXMO',
 'OHXAL',
 'OHXKY',
 'OKXNJ',
 'OKXPA',
 'OTXOR',
 'PAHAR',
 'PAHIN',
 'PAHTN',
 'PBZMD',
 'PHIDE',
 'PIHMT',
 'PIHNV',
 'PIHUT',
 'PUBNM',
 'PUBOK',
 'RAHSC',
 'RIWCO',
 'RIWID',
 'RIWMT',
 'RIWUT',
 'RLXKY',
 'RLXVA',
 'RNKTN',
 'SGFAR',
 'SGFOK',
 'SHVOK',
 'SLCAZ',
 'SLCNV',
 'SLCWY',
 'TFXID',
 'TSATX',
 'UNRMT',
 'UNRNE']

med_cwast = ['AKQNC',
 'AMAOK',
 'ARXIA',
 'ARXMN',
 'BGMPA',
 'BOXCT',
 'BOXMA',
 'BROTX',
 'BTVNY',
 'BTVVT',
 'BYZWY',
 'CAEGA',
 'CHSGA',
 'CHSSC',
 'CYSNE',
 'DVNIL',
 'EAXKS',
 'EPZTX',
 'FSDIA',
 'FSDMN',
 'FSDNE',
 'GIDKS',
 'GLDCO',
 'GSPGA',
 'GSPSC',
 'HUNAL',
 'ILMNC',
 'ILMSC',
 'ILNIN',
 'ILNKY',
 'IWXMI',
 'IWXOH',
 'JANLA',
 'JAXGA',
 'LCHTX',
 'LIXMS',
 'LMKIN',
 'LOTIN',
 'LSXIL',
 'LWXMD',
 'LWXWV',
 'MAFNM',
 'MEGAR',
 'MFLFL',
 'MHXNC',
 'MLBFL',
 'MOBFL',
 'MOBMS',
 'MPXWI',
 'MRXVA',
 'OAXIA',
 'OKXCT',
 'OKXNY',
 'OUNTX',
 'PAHIL',
 'PAHKY',
 'PAHMO',
 'PBZOH',
 'PBZWV',
 'PHIMD',
 'PHINJ',
 'PHIPA',
 'PQRWA',
 'PSRCA',
 'RLXOH',
 'RNKNC',
 'RNKWV',
 'SGFKS',
 'SHVAR',
 'TAEAL',
 'TAEGA',
 'TSAAR']

big_cwast = ['ABQNM',
 'ABRSD',
 'AKQVA',
 'ALYNY',
 'AMATX',
 'APXMI',
 'ARXWI',
 'BGMNY',
 'BISND',
 'BMXAL',
 'BOIID',
 'BOIOR',
 'BOUCO',
 'BUFNY',
 'BYZMT',
 'CAESC',
 'CARME',
 'CLEOH',
 'CRPTX',
 'CTPPA',
 'CYSWY',
 'DDCKS',
 'DLHMN',
 'DLHWI',
 'DMXIA',
 'DTXMI',
 'DVNIA',
 'EAXMO',
 'EKACA',
 'EPZNM',
 'EWXTX',
 'FFCGA',
 'FGFMN',
 'FGFND',
 'FGZAZ',
 'FSDSD',
 'FWDTX',
 'GGWMT',
 'GIDNE',
 'GJTCO',
 'GJTUT',
 'GLDKS',
 'GRBWI',
 'GRRMI',
 'GSPNC',
 'GYXME',
 'GYXNH',
 'HGXTX',
 'HNXCA',
 'ICTKS',
 'ILNOH',
 'ILXIL',
 'INDIN',
 'IWXIN',
 'JANMS',
 'JAXFL',
 'JKLKY',
 'LBFNE',
 'LCHLA',
 'LIXLA',
 'LKNNV',
 'LMKKY',
 'LOTIL',
 'LOXCA',
 'LSXMO',
 'LUBTX',
 'LWXVA',
 'LZKAR',
 'MAFTX',
 'MEGMS',
 'MEGTN',
 'MFRCA',
 'MFROR',
 'MKXWI',
 'MOBAL',
 'MPXMN',
 'MQTMI',
 'MRXTN',
 'MSOID',
 'MSOMT',
 'MTRCA',
 'OAXNE',
 'OHXTN',
 'OTXID',
 'OTXWA',
 'OUNOK',
 'PBZPA',
 'PDTOR',
 'PDTWA',
 'PIHID',
 'PQROR',
 'PSRAZ',
 'PUBCO',
 'RAHNC',
 'REVCA',
 'REVNV',
 'RIWWY',
 'RLXWV',
 'RNKVA',
 'SEWWA',
 'SGFMO',
 'SGXCA',
 'SHVLA',
 'SHVTX',
 'SJTTX',
 'SLCUT',
 'STOCA',
 'TAEFL',
 'TBWFL',
 'TFXMT',
 'TOPKS',
 'TSAOK',
 'TWCAZ',
 'UNRSD',
 'UNRWY',
 'VEFAZ',
 'VEFCA',
 'VEFNV']